substitutions:
  _TAG: develop
  _SERVICE: data-explorer
  _BUILD_DIR: "${PWD}"
steps:
  # Build
  - name: 'docker'
    id: 'base'
    args:
      - 'build'
      - '--push'
      - '--build-arg=tag=${_TAG}'
      - '--tag=gcr.io/${PROJECT_ID}/${_SERVICE}:${_TAG}'
      - '${_BUILD_DIR}'
