options:
  substitutionOption: "ALLOW_LOOSE"
substitutions:
  _TAG: develop
  _SERVICE: panoptes-data-explorer
  _BUILD_DIR: "${PWD}"
steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'base'
    args:
      - 'build'
      - '--push'
      - '--build-arg=tag=${_TAG}'
      - '--tag=gcr.io/${PROJECT_ID}/${_SERVICE}:${_TAG}'
      - '${_BUILD_DIR}'
