options:
  substitutionOption: "ALLOW_LOOSE"
substitutions:
  _TAG: develop
  _IMAGE_NAME: panoptes-data-explorer
  _REPO_URL: https://github.com/panoptes/www.panoptes-data.net

steps:
  # Fetch the repo from github
  - name: gcr.io/cloud-builders/git
    id: "clone-repo"
    args: [ "clone", "${_REPO_URL}" ]
    waitFor: [ "-" ]

  # Pull the cached image.
  - name: 'gcr.io/cloud-builders/docker'
    id: "pull-cached-image"
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG} || exit 0' ]
    waitFor: [ "-" ]

  # Build with cloned panoptes-utils as source directory
  - name: "gcr.io/cloud-builders/docker"
    id: "build-images"
    env:
      - "DOCKER_CLI_EXPERIMENTAL=enabled"
    args:
      - "buildx"
      - "build"
      - "-f=docker/Dockerfile"
      - "--tag=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}"
      - "--cache-from=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}"
      - "POCS"
    waitFor: [ "clone-repo", "pull-cached-image" ]
images:
  - "--tag=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${_TAG}"
